module4/movienight/movienight/urls.py
from django.contrib import admin
from django.urls import path, include
from django_registration.backends.activation.views import RegistrationView

import movienight_auth.views
import movies.views
from movienight_auth.forms import RegistrationForm

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/profile/", movienight_auth.views.profile, name="profile"),
    path(
        "accounts/register/",
        RegistrationView.as_view(form_class=RegistrationForm),
        name="django_registration_register",
    ),
    path("accounts/", include("django_registration.backends.activation.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", movies.views.index),
    path("movie-nights/", movies.views.movie_night_list, name="movie_night_list_ui"),
    path(
        "movie-nights/<int:pk>/",
        movies.views.movie_night_detail,
        name="movie_night_detail_ui",
    ),
    path("search/", movies.views.movie_search, name="movie_search_ui"),
    path("movies/<slug:imdb_id>/", movies.views.movie_detail, name="movie_detail_ui"),
    path("api/v1/", include("movienight.api_urls")),
]

module4/movienight/movies/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from movies.api.views import (
    MovieViewSet,
    MovieNightViewSet,
    MovieNightInvitationViewSet,
    GenreViewSet,
)

router = DefaultRouter()
router.register("movies", MovieViewSet)
router.register("movie-nights", MovieNightViewSet, basename="movienight")
router.register(
    "movie-night-invitations",
    MovieNightInvitationViewSet,
    basename="movienightinvitation",
)
router.register("genres", GenreViewSet)

urlpatterns = [path("", include(router.urls))]

module4/movienight/movies/models.py
from datetime import timedelta

from django.contrib.auth import get_user_model
from django.db import models

UserModel = get_user_model()


class SearchTerm(models.Model):
    class Meta:
        ordering = ["id"]

    term = models.TextField(unique=True)
    last_search = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.term


class Genre(models.Model):
    class Meta:
        ordering = ["name"]

    name = models.TextField(unique=True)

    def __str__(self):
        return self.name


class Movie(models.Model):
    class Meta:
        ordering = ["title", "year"]

    title = models.TextField()
    year = models.PositiveIntegerField()
    runtime_minutes = models.PositiveIntegerField(null=True)
    imdb_id = models.SlugField(unique=True)
    genres = models.ManyToManyField(Genre, related_name="movies")
    plot = models.TextField(null=True, blank=True)
    is_full_record = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.title} ({self.year})"

    @property
    def url(self):
        # required for DRF to render the `url` field in the title and url movie serializer
        return self.pk


class MovieNight(models.Model):
    class Meta:
        ordering = ["creator", "start_time"]

    movie = models.ForeignKey(Movie, on_delete=models.PROTECT)
    start_time = models.DateTimeField()
    creator = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    start_notification_sent = models.BooleanField(default=False)

    @property
    def end_time(self):
        if not self.movie.runtime_minutes:
            return None

        return self.start_time + timedelta(minutes=self.movie.runtime_minutes)

    def __str__(self):
        return f"{self.movie} by {self.creator.email}"


class MovieNightInvitation(models.Model):
    class Meta:
        unique_together = [("invitee", "movie_night")]

    movie_night = models.ForeignKey(
        MovieNight, on_delete=models.CASCADE, related_name="invites"
    )
    invitee = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    attendance_confirmed = models.BooleanField(default=False)
    is_attending = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.movie_night} / {self.invitee.email}"

module4/movienight/movies/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError

from movies.models import MovieNight, MovieNightInvitation

UserModel = get_user_model()


class SearchForm(forms.Form):
    term = forms.CharField(required=False)


class MovieNightForm(forms.ModelForm):
    class Meta:
        model = MovieNight
        fields = ["start_time"]

    def __init__(self, *args, **kwargs):
        super(MovieNightForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit("submit", "Create"))


class InviteeForm(forms.Form):
    email = forms.EmailField()

    _user = False

    def __init__(self, *args, **kwargs):
        super(InviteeForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit("submit", "Invite"))

    def clean_email(self):
        email = self.cleaned_data["email"]
        try:
            # cache for later
            self._user = UserModel.objects.get(email=email)
        except UserModel.DoesNotExist:
            raise ValidationError(f"User with email address '{email}' was not found.")

        return email


class AttendanceForm(forms.ModelForm):
    class Meta:
        model = MovieNightInvitation
        fields = ["is_attending"]

    def __init__(self, *args, **kwargs):
        super(AttendanceForm, self).__init__(*args, **kwargs)
        self.fields["is_attending"].label = "Attending?"
        self.helper = FormHelper()
        self.helper.add_input(Submit("submit", "Update Attendance"))

module4/movienight/movies/api/views.py
from django.shortcuts import redirect
from rest_framework import viewsets, mixins
from rest_framework.decorators import action
from rest_framework.exceptions import PermissionDenied
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from movies.api.permissions import IsInviteePermission, IsCreatorPermission

from movies.api.serializers import (
    MovieSerializer,
    MovieNightSerializer,
    MovieNightInvitationSerializer,
    GenreSerializer,
    MovieSearchSerializer,
    MovieNightInvitationCreationSerializer,
    MovieNightCreateSerializer,
)
from movies.models import Movie, MovieNight, MovieNightInvitation, Genre
from movies.omdb_integration import fill_movie_details, search_and_save


class MovieViewSet(viewsets.ReadOnlyModelViewSet):
    permission_classes = [IsAuthenticated, ]
    queryset = Movie.objects.all()
    serializer_class = MovieSerializer

    def get_object(self,):
      movie_night = super(MovieViewSet, self).get_object()
      return fill_movie_details(movie_night)


    @action(methods=["get"], detail=False)
    def search(self, request):
        search_serializer = MovieSearchSerializer(data=request.GET)

        if not search_serializer.is_valid():
            return Response(search_serializer.errors)

        term = search_serializer.data["term"]

        search_and_save(term)

        movies = self.get_queryset().filter(title__icontains=term)

        page = self.paginate_queryset(movies)

        if page is not None:
            serializer = MovieSerializer(page, many=True, context={"request": request})
            return self.get_paginated_response(serializer.data)

        return Response(
            MovieSerializer(movies, many=True, context={"request": request}).data
        )


class MovieNightViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated & IsCreatorPermission]
    queryset = MovieNight.objects.all()

    def get_serializer_class(self):
      if(self.action in ('create')):
        return MovieNightCreateSerializer
      return MovieNightSerializer

    def get_object(self):
        movie_night = super(MovieNightViewSet, self).get_object()
        if (
            movie_night.creator != self.request.user
            and movie_night.invites.filter(invitee=self.request.user).count() == 0
        ):
            raise PermissionDenied()
        return movie_night

    def get_queryset(self):
        if self.action == "list":
            return self.queryset.filter(creator=self.request.user)
        return super(MovieNightViewSet, self).get_queryset()

    def perform_create(self, serializer):
        serializer.save(creator=self.request.user)

    @action(detail=False)
    def invited(self, request):
        movie_nights = MovieNight.objects.filter(
            invites__in=MovieNightInvitation.objects.filter(invitee=request.user)
        )

        page = self.paginate_queryset(movie_nights)

        if page is not None:
            serializer = MovieNightSerializer(
                page, many=True, context={"request": request}
            )
            return self.get_paginated_response(serializer.data)

        return Response(
            MovieNightSerializer(
                movie_nights, many=True, context={"request": request}
            ).data
        )

    @action(methods=["post"], detail=True)
    def invite(self, request, pk):
        movie_night = self.get_object()
        if movie_night.creator != self.request.user:
            raise PermissionDenied()

        serializer = MovieNightInvitationCreationSerializer(
            movie_night, data=request.data, context={"request": request}
        )

        if not serializer.is_valid():
            return Response(serializer.errors)

        serializer.save()
        return redirect("movienight-detail", (movie_night.pk,))


class MovieNightInvitationViewSet(
    mixins.RetrieveModelMixin,
    mixins.UpdateModelMixin,
    mixins.DestroyModelMixin,
    mixins.ListModelMixin,
    viewsets.GenericViewSet,
):
    serializer_class = MovieNightInvitationSerializer
    permission_classes = [IsAuthenticated & IsInviteePermission]

    def get_queryset(self):
        return MovieNightInvitation.objects.filter(invitee=self.request.user)


class GenreViewSet(viewsets.ModelViewSet):
    queryset = Genre.objects.all()
    serializer_class = GenreSerializer

module4/movienight/movies/views.py
from datetime import timedelta

from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from movies.forms import SearchForm, MovieNightForm, InviteeForm, AttendanceForm
from movies.models import Movie, MovieNight, MovieNightInvitation
from movies.omdb_integration import search_and_save, fill_movie_details


def index(request):
    return render(request, "movies/index.html")


@login_required
def movie_search(request):
    search_form = SearchForm(request.POST)

    if search_form.is_valid() and search_form.cleaned_data["term"]:
        term = search_form.cleaned_data["term"]
        search_and_save(term)
        movie_list = Movie.objects.filter(title__icontains=term)
        did_search = True
    else:
        movie_list = []
        did_search = False

    return render(
        request,
        "movies/search.html",
        {
            "page_group": "search",
            "search_form": search_form,
            "movie_list": movie_list,
            "did_search": did_search,
        },
    )


@login_required
def movie_night_list(request):
    start_time_after = timezone.now() - timedelta(hours=2)
    created_movie_nights = MovieNight.objects.filter(
        creator=request.user, start_time__gt=start_time_after
    )
    invited_movie_nights = MovieNight.objects.filter(
        start_time__gt=start_time_after,
        invites__in=MovieNightInvitation.objects.filter(invitee=request.user),
    )

    return render(
        request,
        "movies/movie_night_list.html",
        {
            "page_group": "movie-nights",
            "created_movie_nights": created_movie_nights,
            "invited_movie_nights": invited_movie_nights,
        },
    )


@login_required
def movie_detail(request, imdb_id):
    movie = get_object_or_404(Movie, imdb_id=imdb_id)
    fill_movie_details(movie)
    if request.method == "POST":
        movie_night_form = MovieNightForm(request.POST)
        if movie_night_form.is_valid():
            movie_night = movie_night_form.save(False)
            movie_night.movie = movie
            movie_night.creator = request.user
            movie_night.save()
            return redirect("movie_night_detail_ui", movie_night.pk)
    else:
        movie_night_form = MovieNightForm()
    return render(
        request,
        "movies/movie_detail.html",
        {"page_group": "search", "movie": movie, "movie_night_form": movie_night_form},
    )


@login_required
def movie_night_detail(request, pk):
    movie_night = get_object_or_404(MovieNight, pk=pk)

    is_creator = movie_night.creator == request.user

    invitee_form = None
    attendance_form = None

    invitees = {invitation.invitee for invitation in movie_night.invites.all()}

    is_in_the_past = movie_night.start_time < timezone.now()

    if not is_creator:
        if request.user not in invitees:
            raise PermissionDenied("You do not have access to this MovieNight")

        invitation = movie_night.invites.filter(invitee=request.user).first()

        if not is_in_the_past and request.method == "POST":
            attendance_form = AttendanceForm(request.POST, instance=invitation)
            if attendance_form.is_valid():
                attendance_form.save()
        else:
            attendance_form = AttendanceForm(instance=invitation)
    else:
        if not is_in_the_past and request.method == "POST":
            invitee_form = InviteeForm(request.POST)

            if invitee_form.is_valid():
                invitee = invitee_form._user

                if invitee == request.user or invitee in invitees:
                    invitee_form.add_error(
                        "email", "That user is the creator or already invited"
                    )
                else:
                    MovieNightInvitation.objects.create(
                        invitee=invitee, movie_night=movie_night
                    )
                    return redirect(request.path)  # effectively, just reload the page
        else:
            invitee_form = InviteeForm()

    return render(
        request,
        "movies/movie_night_detail.html",
        {
            "page_group": "movie-nights",
            "movie_night": movie_night,
            "is_creator": is_creator,
            "invitee_form": invitee_form,
            "attendance_form": attendance_form,
            "is_in_the_past": is_in_the_past,
        },
    )

module4/movienight/movies/templates/movies/index.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <div class="col text-center">
            <h1>Welcome to <span class="movie">Movie</span><span class="night">Night</span></h1>
            <p class="mb-3">Schedule a Movie Night with your friends.</p>
            {% if request.user.is_anonymous %}
            <p>
                Please <a href="{% url 'login' %}">Log In</a> or <a href="{% url 'django_registration_register' %}">Sign Up</a>.
            </p>
            {% else %}
            <p>
                Check out your list of <a href="{% url 'movie_night_list_ui' %}">Movie Nights</a>,
                or perform a <a href="{% url 'movie_search_ui' %}">Movie Search</a> to create your own.
            </p>
            {% endif %}
        </div>
    </div>

{% endblock %}

module4/movienight/movies/templates/movies/movie_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}{{ movie.title }} ({{ movie.year }}){% endblock %}
{% block content %}
    <div class="row">
        <div class="col">
            <h2>{{ movie.title }}</h2>
            <p>{% for genre in movie.genres.all %}{{ genre.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
            <p>{{ movie.plot }}</p>
            <h3>Create Movie Night</h3>
            <p>
                {% crispy movie_night_form %}
            </p>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script>
      flatpickr('#id_start_time', {
        enableTime: true
      })
    </script>
{% endblock %}

module4/movienight/movies/templates/movies/movie_night_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Movie Night for {{ movie_night.movie.title }} ({{ movie_night.movie.year }}){% endblock %}
{% block content %}
    <div class="col">
        <div class="row">
            <h2>Movie Night for {{ movie_night.movie.title }} ({{ movie_night.movie.year }})</h2>
            <p class="mb-3">
                Scheduled for: {{ movie_night.start_time }}
                {% if movie_night.end_time %}(until {{ movie_night.end_time }}){% endif %}
            </p>
            <p class="mb-3">
                {{ movie_night.movie.plot }}
            </p>
            <h3>Invites</h3>
            <ul>
                {% for invite in movie_night.invites.all %}
                    <li>
                        {{ invite.invitee.email }}
                        ({% if invite.attendance_confirmed %}Is {% if not invite.is_attending %}not {% endif %}attending{% else %}Awaiting response{% endif %})
                    </li>
                {% empty %}
                    <li>No invites yet</li>
                {% endfor %}
            </ul>
            {% if is_in_the_past %}
                <h4>This Movie Night is in the past, and can&rsquo;t be edited.</h4>
            {% else %}
                {% if is_creator %}
                    <h4>Invite someone else</h4>
                    <p>{% crispy invitee_form %}</p>
                {% else %}
                    <h4>Your attendance</h4>
                    {% crispy attendance_form %}
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endblock %}

module4/movienight/movies/templates/movies/movie_night_list.html
{% extends "base.html" %}
{% block title %}Movie Nights{% endblock %}
{% block content %}
<div class="row">
    <div class="col">
        <h2>My Movie Nights</h2>
        <ul>
        {% for created_movie_night in created_movie_nights %}
            <li>
                <a href="{% url 'movie_night_detail_ui' created_movie_night.pk %}">{{ created_movie_night.movie.title }} on {{ created_movie_night.start_time }}</a>
            </li>
        {% empty %}
            <li>You haven&rsquo;t created any Movie Nights yet. Search for a movie to create one.</li>
        {% endfor %}
        </ul>
        <h2>Invited Movie Nights</h2>
    <ul>
        {% for invited_movie_night in invited_movie_nights %}
            <li>
                <a href="{% url 'movie_night_detail_ui' invited_movie_night.pk %}">{{ invited_movie_night.movie.title }} on {{ invited_movie_night.start_time }}</a>
            </li>
        {% empty %}
            <li>You haven&rsquo;nt been invited to any Movie Nights.</li>
        {% endfor %}
    </ul>
    </div>
</div>
{% endblock %}

module4/movienight/movies/templates/movies/search.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    {% if did_search %}
        Search results for '{{ search_form.term.value }}'
    {% else %}
        Movie Search
    {% endif %}
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col">
            <h2>Movie Search</h2>
            <form class="row row-cols-lg-auto g-3 align-items-center" method="post">
                {% csrf_token %}
                <div class="col-12">
                    {{ search_form.term|as_crispy_field }}
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-primary mt-3">Search</button>
                </div>
            </form>
        </div>
    </div>
    {% if did_search %}
        <div class="row">
            <div class="col">
                {% if movie_list %}
                    <ul>
                        {% for movie in movie_list %}
                            <li>
                                {{ movie.title }} ({{ movie.year }}) <a
                                    href="{% url "movie_detail_ui" movie.imdb_id %}">[Details]</a>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <h3>No results found.</h3>
                {% endif %}
            </div>
        </div>
    {% endif %}
{% endblock %}